src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * 
     * @Assert\NotBlank(message = "Please fill the fields", groups={"userVal"})
     * 
     * @Assert\Email(message ="The email is not a valid email.", groups={"userVal"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     *      
     * @Assert\NotBlank(message = "Please fill the fields", groups={"userVal"})
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $middleName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $houseNumber;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLogin;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="user")
     */
    private $products;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /************************* Public Functions **************************/

    public function __construct()
    {
        $this->products = new ArrayCollection();        
    }

    /**
     * Returns the fullname with firstname, middlename and lastname
     * If the username is empty then return the email address
     * 
     * @return string Full name or Email address
     */
    public function getFullname(): string
    {
        $username = trim(str_replace(' ', ' ', $this->getFirstName().' '.$this->getMiddleName().' '.$this->getLastName()));

        if(empty($username)) {
            return $this->getEmail();
        } else {
            return $username;
        }
    }

    /**
     * Returns the fullname with firstname, middlename and lastname
     * 
     * @return string Full Name
     */
    public function getPersonName(): string
    {
        $username = trim(str_replace(' ', ' ', $this->getFirstName().' '.$this->getMiddleName().' '.$this->getLastName()));

        return $username;        
    }

    /**
     * Returns the fullname with firstname, middlename and lastname
     * 
     * @return string Full Name
     */
    public function getAddress(): string
    {
        $address = trim(str_replace(' ', ' ', $this->getStreet().' '.$this->getHouseNumber().' '.$this->getCity().' '.$this->getPostalCode()));

        return $address;        
    }

    /************************* Specific getters/setters **************************/

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    public function setMiddleName(?string $middleName): self
    {
        $this->middleName = $middleName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getHouseNumber(): ?string
    {
        return $this->houseNumber;
    }

    public function setHouseNumber(?string $houseNumber): self
    {
        $this->houseNumber = $houseNumber;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setUser($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getUser() === $this) {
                $product->setUser(null);
            }
        }

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }
}

templates/dashboard.html.twig
{% extends "base/base.html.twig" %}
{% import "base/menu_bar.html.twig" as menu %}

{% block body %}
   <!-- Layout wrapper -->
   <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">

         <!-- Left menu bar -->
         {{ menu.writeLeftBar(showUser) }}

        <!-- Layout container -->
        <div class="layout-page">
         {{ menu.writeTopBar(user) }}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-12 mb-4 order-0">
                  <div class="card">
                    <div class="d-flex align-items-end row">
                      <div class="col-sm-8">
                        <div class="card-body">
                          <p class="mb-4">
                            {{ 'dashboard.page.introduction'|trans|raw }}
                          </p>
                          {% if showUser %}
                            <a href="{{ path('user-list') }}" class="btn btn-sm btn-outline-primary">View Users</a>
                          {% endif %}
                        </div>
                      </div>
                      <div class="col-sm-4 text-center text-sm-left">
                        <div class="card-body pb-0 px-0 px-md-4 mb-4">
                          <img
                            src="{{ asset('img/illustrations/girl-doing-yoga-light.png') }}"
                            height="140"
                            alt="View Badge User"
                            data-app-dark-img="illustrations/man-with-laptop-dark.png"
                            data-app-light-img="illustrations/man-with-laptop-light.png"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Order Statistics -->
                <div class="col-md-6 col-lg-6 col-xl-6 order-0 mb-4">
                  <div class="card h-100">
                    <div class="card-header d-flex align-items-center justify-content-between pb-0">
                      <div class="card-title mb-0">
                        <h5 class="m-0 me-2">Product Statistics</h5>
                      </div>
                    </div>
                    <div class="card-body">
                      {% set totalProduct = 0 %}    
                      {% for product in products %}            
                            {% set totalProduct = totalProduct + product.total %}        
                      {% endfor %} 
                      <div class="d-flex justify-content-between align-items-center mb-5">
                        <div class="d-flex flex-column align-items-center gap-1 mt-4">
                          <h2 class="mb-2">{{ totalProduct }}</h2>
                          <span>Total Products</span>
                        </div>
                        <div id="orderStatisticsChart"></div>
                      </div>
                      <ul class="p-0 m-0">
                        {% for product in products %}
                          <li class="d-flex mb-4 pb-1">
                            <div class="avatar flex-shrink-0 me-3">
                              <span class="avatar-initial rounded bg-label-primary"><i class="bx bx-mobile-alt"></i></span>
                            </div>
                            <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">                           
                              <div class="me-2">
                                <h6 class="mb-0">{{ product.item.category }}</h6>
                                <small class="text-muted">{{ product.item.name }}</small>
                              </div>
                              <div class="user-progress">
                                <small class="fw-semibold">{{ product.total }}</small>
                              </div>
                            </div>
                          </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <!--/ Order Statistics -->
                
                <!-- user -->
                {% if showUser %}
                <div class="col-md-6 col-lg-6 order-2 mb-4">
                  <div class="card h-100">
                    <div class="card-header d-flex align-items-center justify-content-between">
                      <h5 class="card-title m-0 me-2">Users Overview</h5>
                      
                    </div>
                    <div class="card-body">
                      <ul class="p-0 m-0">
                        {% for user in userlist|slice(0,6) %}
                          <li class="d-flex mb-4 pb-1">
                            <div class="avatar flex-shrink-0 me-3">
                              <span class="avatar-initial rounded bg-label-primary"><i class="bx bx-user"></i></span>
                            </div>
                            <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                              <div class="me-2">
                                <small class="text-muted d-block mb-1">{{ user.personName }}</small>
                                <h6 class="mb-0">{{user.email}}</h6>
                              </div>
                              <div class="user-progress d-flex align-items-center gap-1">
                                <h6 class="mb-0">{{ user.country }}</h6>
                              </div>
                            </div>
                          </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <!--/ Transactions -->
                {% endif %}
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    
{% endblock %}

templates/index.html.twig
{% extends "base/base.html.twig" %}

{% block body %}
   <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-x">
         <div class="col-sm-8">
            <div class="card">
               <div class="card-body">
                  <!-- Logo -->
                  <div class="app-brand justify-content-center mb-5">
                     <a href="{{website|default('/')}}" class="app-brand-link gap-2">
                        <span class="app-brand-logo demo">
                           <img src="{{ asset('img/logo.jpg')}}" width="30px" height="40px"/>
                        </span>
                        <span class="app-brand-text demo text-body fw-bolder">{{ 'home.page.title'|trans|raw }}</span>
                     </a>
                  </div>
                  <!-- /Logo -->

                  <div class="d-flex align-items-end row">
                     <div class="col-sm-7">
                     <div class="card-body">
                        <h5 class="card-title text-primary">{{ 'home.page.sub_title'|trans|raw }} 🎉</h5>
                        <p class="mb-4">{{ 'home.page.introduction'|trans|raw }}</p>
                        </div>
                     </div>
                     <div class="col-sm-5 text-center text-sm-left">
                     <div class="card-body pb-0 px-0 px-md-4">
                        <img src="{{ asset('img/illustrations/man-with-laptop-light.png')}}" height="140" alt="View Badge User" data-app-dark-img="illustrations/man-with-laptop-dark.png" data-app-light-img="illustrations/man-with-laptop-light.png">
                     </div>
                     </div>
                  </div>
                  <p class="text-center mt-5">
                     <a href="{{ path('login') }}" class="btn btn-primary btn-lg">{{ 'home.button.login'|trans|raw }}</a>
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
{% endblock %}

templates/login.html.twig
{% extends "base/base.html.twig" %}

{% block body %}
   {{ form_start(form, {'attr': {'novalidate': 'novalidate'} }) }}
   {{ form_errors(form) }}
      <div class="container-xxl">
         <div class="authentication-wrapper authentication-basic container-p-y">
         <div class="authentication-inner">
            <!-- Register -->
            <div class="card">
               <div class="card-body">
               <!-- Logo -->
               <div class="app-brand justify-content-center">
                  <a href="{{website|default('/')}}" class="app-brand-link gap-2">
                     <span class="app-brand-logo demo">
                        <img src="{{ asset('img/logo.jpg')}}" width="30px" height="40px"/>
                     </span>
                     <span class="app-brand-text demo text-body fw-bolder">{{ 'home.page.title'|trans|raw }}</span>
                  </a>
               </div>
               <!-- /Logo -->
               <p class="mb-4">{{ 'login.page.introduction'|trans|raw }}</p>
                  <div class="mb-3">
                     {{ form_row(form.email) }}
                  </div>
                  <div class="mb-3 form-password-toggle">
                     {{ form_row(form.password) }}                     
                  </div>                  
                  <div class="mb-3">
                     {{ form_row(form.login) }} 
                  </div>
                  <p class="text-center">
                     <span>New on our platform?</span>
                     <a href="{{ path('register')}}"><span>Create an account</span></a>
                  </p>
               </div>
            </div>
            <!-- /Register -->
         </div>
         </div>
      </div>
   {{ form_end(form) }}
{% endblock %}

templates/product.html.twig
{% extends "base/base.html.twig" %}
{% import "base/menu_bar.html.twig" as menu %}

{% block body %}
  {{ form_start(form, {'attr': {'novalidate': 'novalidate'} }) }}
  {{ form_errors(form) }}
   <!-- Layout wrapper -->
   <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">

        <!-- Left menu bar -->
        {{ menu.writeLeftBar(showUser) }}

        <!-- Layout container -->
        <div class="layout-page">
         {{ menu.writeTopBar(user) }}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4">Product</h4>
              <div class="row">
                <div class="col-md-12">                  
                  <div class="card mb-4">
                    <h5 class="card-header">Product Details</h5>
                    <div class="card-body">
                        <div class="row">
                          <div class="mb-3 col-md-12">
                            {{ form_row(form.name) }}
                          </div>
                          <div class="mb-3 col-md-12">
                            {{ form_row(form.description) }}
                          </div>
                          <div class="mb-3 col-md-12">
                            {{ form_row(form.price) }}
                          </div>
                          <div class="mb-3 col-md-12">
                            {{ form_row(form.category) }}
                          </div>                                                   
                        </div>
                        <div class="row mt-2">
                          <div class="mb-3 col-md-1">{{ form_row(form.submit) }} </div>
                          <div class="mb-3 col-md-1">{{ form_row(form.cancel) }} </div>
                        </div>
                      </form>
                    </div>
                    <!-- /Account -->
                  </div>
                </div>
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

    {{ form_end(form, {'render_rest': false}) }}    
{% endblock %}

templates/product_list.html.twig
{% extends "base/base.html.twig" %}
{% import "base/menu_bar.html.twig" as menu %}

{% block body %}
   <!-- Layout wrapper -->
   <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">

         <!-- Left menu bar -->
         {{ menu.writeLeftBar(showUser) }}

        <!-- Layout container -->
        <div class="layout-page">
         {{ menu.writeTopBar(user) }}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4">Product List</h4>
              <div class="row">
                <div class="col-md-12">
                  
                  {% if productlist|length == 0 %}
                    <div class="card text-center">
                      <div class="card-body">
                        <h5 class="card-title">Product Overview</h5>
                        <p class="card-text">Here you can add the products.</p>
                        <a href="{{ path('product') }}" class="btn btn-primary m-5">ADD PRODUCTS</a>
                      </div>
                      
                    </div>
                  {% else %}
                  <a href="{{ path('product') }}" class="btn btn-primary mb-4">ADD PRODUCTS</a>

                  <!-- Hoverable Table rows -->
              <div class="card">
                <div class="table-responsive text-nowrap">                  
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>{{ 'product.form.name.label'|trans|raw }}</th>
                        <th>{{ 'product.form.description.label'|trans|raw }}</th>
                        <th>{{ 'product.form.price.label'|trans|raw }}</th>
                        <th>{{ 'product.form.category.label'|trans|raw }}</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      {% for product in productlist %}
                        <tr>
                          <td><b>{{ product.name }}</b></td>
                          <td>{{ product.description }}</td>
                          <td>{{ product.price|format_currency('EUR') }}</td>
                          <td>{{ product.category }}</td>
                          <td>
                            <a class="btn btn-icon btn-primary" href="{{ path('product', {'id': product.id})}}"><i class="bx bx-edit me-1"></i></a>
                          <a class="btn btn-icon btn-danger" href="{{ path('delete-product', {'id': product.id})}}"><i class="bx bx-trash me-1"></i></a
                          >
                            
                          </td>
                        </tr>                        
                      {% endfor %}                      
                    </tbody>
                  </table>                 
                </div>
              </div>
              <!--/ Hoverable Table rows -->
              {% endif %}

                </div>
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

{% endblock %}

templates/register.html.twig
{% extends "base/base.html.twig" %}

{% block body %}
   {{ form_start(form, {'attr': {'novalidate': 'novalidate'} }) }}
   {{ form_errors(form) }}
      <div class="container-xxl">
         <div class="authentication-wrapper authentication-basic container-p-y">
         <div class="authentication-inner">
            <!-- Register -->
            <div class="card">
               <div class="card-body">
               <!-- Logo -->
               <div class="app-brand justify-content-center">
                  <a href="{{website|default('/')}}" class="app-brand-link gap-2">
                     <span class="app-brand-logo demo">
                        <img src="{{ asset('img/logo.jpg')}}" width="30px" height="40px"/>
                     </span>
                     <span class="app-brand-text demo text-body fw-bolder">{{ 'home.page.title'|trans|raw }}</span>
                  </a>
               </div>
               <!-- /Logo -->
               <p class="mb-4">{{ 'register.page.introduction'|trans|raw }}</p>
                  <div class="mb-3">
                     {{ form_row(form.email) }}
                  </div>
                  <div class="mb-3 form-password-toggle">
                     {{ form_row(form.password) }}                     
                  </div>
                               
                  <div class="mb-3">
                     {{ form_row(form.register) }} 
                  </div>               
                  <p class="text-center">
                     <span>Already have an account?</span>
                     <a href="{{ path('login')}}"><span>Sign in instead</span></a>
                  </p>
               </div>
            </div>
            <!-- /Register -->
         </div>
         </div>
      </div>
   {{ form_end(form) }}
{% endblock %}

templates/user_list.html.twig
{% extends "base/base.html.twig" %}
{% import "base/menu_bar.html.twig" as menu %}

{% block body %}
   <!-- Layout wrapper -->
   <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">

         <!-- Left menu bar -->
         {{ menu.writeLeftBar(showUser) }}

        <!-- Layout container -->
        <div class="layout-page">
         {{ menu.writeTopBar(user) }}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <h4 class="fw-bold py-3 mb-4">User List</h4>
              <div class="row">
                <div class="col-md-12">                  
                  <!-- Hoverable Table rows -->
              <div class="card">
                <div class="table-responsive text-nowrap">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>{{ 'user.form.email.label'|trans|raw }}</th>
                        <th>{{ 'user.form.name.label'|trans|raw }}</th>
                        <th>{{ 'user.form.phone.label'|trans|raw }}</th>
                        <th>{{ 'user.form.address.label'|trans|raw }}</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      {% for user in userlist %}
                        <tr>
                          <td><b>{{ user.email }}</b></td>
                          <td>{{ user.personName }}</td>
                          <td>{{ user.phone }}</td>
                          <td>{{ user.address }}</td>
                          <td>
                            <div class="dropdown">
                              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                <i class="bx bx-dots-vertical-rounded"></i>
                              </button>
                              <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{ path('user', {'id': user.id})}}"
                                  ><i class="bx bx-edit-alt me-1"></i> Edit</a
                                >
                                <a class="dropdown-item" href="{{ path('delete-user', {'id': user.id})}}"
                                  ><i class="bx bx-trash me-1"></i> Delete</a
                                >
                              </div>
                            </div>
                          </td>
                        </tr>                        
                      {% endfor %}                      
                    </tbody>
                  </table>
                </div>
              </div>
              <!--/ Hoverable Table rows -->

                </div>
              </div>
            </div>
            <!-- / Content -->


            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->

{% endblock %}